### ISSUE TITLE
Building simple example on Fedora 28

### ISSUE THREAD

**Issue by ZaWertun** [Papierkorb/qt5.cr#18]
I succeeded building simple example after adding `/usr/lib64` to QT_LIBS_DIR in file `config/find_paths.yml` (I have Fedora x64).
Part of find_paths.yml after change:
```yaml
  QT_LIBS_DIR:
    try:
      - shell: "{QMAKE} -query QT_INSTALL_LIBS"
      - "{QTDIR}/lib"
      - "/usr/lib"
      - "/usr/lib64"
      - "/usr/local/lib"
```
